server {
    listen 80;
    listen [::]:80;
    server_name ${EDGE_DOMAIN} ${SUB_DOMAIN};

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/edge-infra-acme;
        default_type text/plain;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name ${SUB_DOMAIN};

    ssl_certificate /etc/letsencrypt/live/${CERT_NAME}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${CERT_NAME}/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    add_header X-Content-Type-Options nosniff always;

    root /var/www/edge-infra-subscription;
    location = /${SUBSCRIPTION_FILE} {
        default_type application/yaml;
        try_files /${SUBSCRIPTION_FILE} =404;
    }

    location / {
        return 404;
    }
}
