server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name ${SUB_DOMAIN};

    ssl_certificate /etc/letsencrypt/live/${SUB_DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${SUB_DOMAIN}/privkey.pem;

    root /var/www/sub;
    location = /edge.yaml {
        default_type application/yaml;
        try_files /edge.yaml =404;
    }
}
